disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - vertical_whitespace
  - todo
  - identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - OCM/Resources/Localizables/LocalizableConstants.swift

variable_name:
  excluded: # excluded via string array
    - id
    - on
