disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - todo

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

variable_name:
  excluded: # excluded via string array
    - id
    - on
